spring:
  application:
    name: chattravel
  datasource:
    url: jdbc:mysql://chattraveldb.cn22qsoeogen.ap-northeast-2.rds.amazonaws.com:3306/chattravel
    username: root
    password: chattravel00!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
#server:
#  port: 8081
